# Generated by Django 4.1.4 on 2022-12-18 07:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clintlogo', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Clint',
                'verbose_name_plural': 'Clint',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('comments', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('shortdesc', models.CharField(blank=True, max_length=500, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Features',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='HomeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=100, null=True)),
                ('title2', models.CharField(blank=True, max_length=100, null=True)),
                ('shape', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('Clintnumber', models.CharField(blank=True, max_length=10, null=True)),
                ('featuretitle', models.CharField(blank=True, max_length=100, null=True)),
                ('storyaboutustitle', models.CharField(blank=True, max_length=100, null=True)),
                ('storyaboutusitem1', models.CharField(blank=True, max_length=100, null=True)),
                ('storyaboutusdesc1', models.CharField(blank=True, max_length=1000, null=True)),
                ('storyaboutusitem2', models.CharField(blank=True, max_length=50, null=True)),
                ('storyaboutusdesc2', models.CharField(blank=True, max_length=1000, null=True)),
                ('storyaboutusbanner1', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('storyaboutusbanner2', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('singuptitle', models.CharField(blank=True, max_length=100, null=True)),
                ('signupdesc', models.CharField(blank=True, max_length=100, null=True)),
                ('chooseustitle', models.CharField(blank=True, max_length=100, null=True)),
                ('chooseusdesc', models.CharField(blank=True, max_length=1000, null=True)),
                ('sucessrate', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home_Setting',
                'verbose_name_plural': 'Home_Setting',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('shortdesc', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('dateyear', models.CharField(blank=True, max_length=20, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=25, null=True)),
                ('backgroundphoto', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/modules/')),
                ('description', ckeditor.fields.RichTextField()),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='website.projects')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
    ]
