# Generated by Django 4.1.4 on 2022-12-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_subscrib'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesetting',
            name='logodesc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
