# Generated by Django 4.1.4 on 2023-01-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_about_jobs_solutionstandard_alter_projects_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Value', 'verbose_name_plural': 'About Value'},
        ),
    ]
