# Generated by Django 4.1.4 on 2023-01-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='resume',
            field=models.FileField(upload_to='static/modules/'),
        ),
    ]
