# Generated by Django 4.1.4 on 2023-01-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_applyjob_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='resume',
            field=models.FileField(upload_to='static/resumes/'),
        ),
    ]
