# Generated by Django 4.1.4 on 2023-01-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_applyjob_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applyjob', to='website.jobs'),
        ),
    ]
