# Generated by Django 4.1.4 on 2023-01-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_applyjob_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjob',
            old_name='jobs',
            new_name='linked_jobs',
        ),
    ]
