# Generated by Django 4.1.4 on 2023-01-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_jobs_applyjob_linked_jobs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clint',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Client'},
        ),
    ]
