# Generated by Django 4.1.4 on 2023-01-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_clint_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='ordering',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='ordering',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
