# Generated by Django 4.1.4 on 2023-01-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_subscrib_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='backgroundphoto',
        ),
    ]
