# Generated by Django 4.1.4 on 2023-01-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_modules_backgroundphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='shortdesc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
