# Generated by Django 4.1.4 on 2023-01-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_about_valuedesc_alter_contact_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='shortdesc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
