# Generated by Django 4.1.4 on 2023-02-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_jobs_shortdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionstandard',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solutionstandard',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
