# Generated by Django 4.1.4 on 2023-02-09 08:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_solutionstandard_title_alter_solutionstandard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesetting',
            name='carrerdesc',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='solutionstandard',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
