# Generated by Django 4.1.4 on 2023-02-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_homesetting_carrerdesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homesetting',
            old_name='aboutbanner1',
            new_name='aboutbanner',
        ),
        migrations.RemoveField(
            model_name='homesetting',
            name='aboutbanner2',
        ),
    ]
