# Generated by Django 4.1.4 on 2023-02-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_rename_aboutbanner1_homesetting_aboutbanner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='valuedesc',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='valuename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
